from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import QMediaContent, QMediaPlayer
from PyQt5.QtMultimediaWidgets import QVideoWidget
import sys

class VideoWidget(QVideoWidget):

    def __init__(self, parent=None):
        super(VideoWidget, self).__init__(parent)

        self.setSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)

        p = self.palette()
        p.setColor(QtGui.QPalette.Window, QtCore.Qt.black)
        self.setPalette(p)

        self.setAttribute(QtCore.Qt.WA_OpaquePaintEvent)

    def keyPressEvent(self, event):
        if event.key() == QtCore.Qt.Key_Escape and self.isFullScreen():
            self.setFullScreen(False)
            event.accept()
        elif event.key() == QtCore.Qt.Key_Enter and event.modifiers() & Qt.Key_Alt:
            self.setFullScreen(not self.isFullScreen())
            event.accept()
        else:
            super(VideoWidget, self).keyPressEvent(event)

    def mouseDoubleClickEvent(self, event):
        self.setFullScreen(not self.isFullScreen())
        event.accept()


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1173, 855)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #-----------------------------------Menu Bar-----------------------------------------------#
        main_menu = MainWindow.menuBar()
        file_menu = main_menu.addMenu('File')
        open_file = QtWidgets.QAction('Open', MainWindow)
        open_file.setShortcut("Ctrl+O")
        open_file.setStatusTip("Open Video File")
        file_menu.addAction(open_file)
        MainWindow.setMenuBar(main_menu)
        #-----------------------------------Menu Bar-----------------------------------------------#
        #---------------------------------Video Player---------------------------------------------#
        self.player = QMediaPlayer(None, QMediaPlayer.VideoSurface)
        self.videoWidget = VideoWidget()
        self.player.setVideoOutput(self.videoWidget)
        # self.player.setGeometry(QtCore.QReact(30,670, 200, 200))
        #---------------------------------Video Player---------------------------------------------#


        self.Anger = QtWidgets.QLabel(self.centralwidget)
        self.Anger.setGeometry(QtCore.QRect(30, 80, 80, 21))
        self.Anger.setObjectName("Anger")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 121, 21))
        self.label_2.setObjectName("label_2")
        self.Suprise = QtWidgets.QLabel(self.centralwidget)
        self.Suprise.setGeometry(QtCore.QRect(30, 160, 80, 21))
        self.Suprise.setObjectName("Suprise")
        self.Disgust = QtWidgets.QLabel(self.centralwidget)
        self.Disgust.setGeometry(QtCore.QRect(30, 200, 80, 21))
        self.Disgust.setObjectName("Disgust")
        self.Distress = QtWidgets.QLabel(self.centralwidget)
        self.Distress.setGeometry(QtCore.QRect(30, 240, 80, 21))
        self.Distress.setObjectName("Distress")
        self.Fear = QtWidgets.QLabel(self.centralwidget)
        self.Fear.setGeometry(QtCore.QRect(30, 280, 80, 21))
        self.Fear.setObjectName("Fear")
        self.Embaressment = QtWidgets.QLabel(self.centralwidget)
        self.Embaressment.setGeometry(QtCore.QRect(30, 320, 151, 21))
        self.Embaressment.setObjectName("Embaressment")
        self.Contemt = QtWidgets.QLabel(self.centralwidget)
        self.Contemt.setGeometry(QtCore.QRect(30, 350, 101, 21))
        self.Contemt.setObjectName("Contemt")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(160, 520, 80, 21))
        self.label_9.setObjectName("label_9")
        self.happiness = QtWidgets.QLabel(self.centralwidget)
        self.happiness.setGeometry(QtCore.QRect(50, 10, 151, 41))
        self.happiness.setObjectName("happiness")
        self.spinBox_9 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_9.setGeometry(QtCore.QRect(210, 520, 52, 30))
        self.spinBox_9.setObjectName("spinBox_9")
        self.spinBox_10 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_10.setGeometry(QtCore.QRect(210, 560, 52, 30))
        self.spinBox_10.setObjectName("spinBox_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(160, 560, 80, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(160, 640, 80, 21))
        self.label_12.setObjectName("label_12")
        self.spinBox_11 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_11.setGeometry(QtCore.QRect(210, 600, 52, 30))
        self.spinBox_11.setObjectName("spinBox_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(160, 600, 80, 21))
        self.label_13.setObjectName("label_13")
        self.spinBox_12 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_12.setGeometry(QtCore.QRect(210, 640, 52, 30))
        self.spinBox_12.setObjectName("spinBox_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(160, 720, 80, 21))
        self.label_14.setObjectName("label_14")
        self.spinBox_13 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_13.setGeometry(QtCore.QRect(210, 680, 52, 30))
        self.spinBox_13.setObjectName("spinBox_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(160, 680, 80, 21))
        self.label_15.setObjectName("label_15")
        self.spinBox_14 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_14.setGeometry(QtCore.QRect(210, 720, 52, 30))
        self.spinBox_14.setObjectName("spinBox_14")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(290, 600, 80, 21))
        self.label_16.setObjectName("label_16")
        self.spinBox_15 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_15.setGeometry(QtCore.QRect(340, 640, 52, 30))
        self.spinBox_15.setObjectName("spinBox_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(290, 560, 80, 21))
        self.label_17.setObjectName("label_17")
        self.spinBox_16 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_16.setGeometry(QtCore.QRect(340, 680, 52, 30))
        self.spinBox_16.setObjectName("spinBox_16")
        self.spinBox_17 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_17.setGeometry(QtCore.QRect(340, 520, 52, 30))
        self.spinBox_17.setObjectName("spinBox_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(290, 520, 80, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(290, 640, 80, 21))
        self.label_19.setObjectName("label_19")
        self.spinBox_18 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_18.setGeometry(QtCore.QRect(340, 600, 52, 30))
        self.spinBox_18.setObjectName("spinBox_18")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(290, 720, 80, 21))
        self.label_20.setObjectName("label_20")
        self.spinBox_19 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_19.setGeometry(QtCore.QRect(340, 720, 52, 30))
        self.spinBox_19.setObjectName("spinBox_19")
        self.spinBox_20 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_20.setGeometry(QtCore.QRect(340, 560, 52, 30))
        self.spinBox_20.setObjectName("spinBox_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(290, 680, 80, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(420, 600, 80, 21))
        self.label_22.setObjectName("label_22")
        self.spinBox_21 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_21.setGeometry(QtCore.QRect(470, 640, 52, 30))
        self.spinBox_21.setObjectName("spinBox_21")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(420, 560, 80, 21))
        self.label_23.setObjectName("label_23")
        self.spinBox_22 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_22.setGeometry(QtCore.QRect(470, 680, 52, 30))
        self.spinBox_22.setObjectName("spinBox_22")
        self.spinBox_23 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_23.setGeometry(QtCore.QRect(470, 520, 52, 30))
        self.spinBox_23.setObjectName("spinBox_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(420, 520, 80, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(420, 640, 80, 21))
        self.label_25.setObjectName("label_25")
        self.spinBox_24 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_24.setGeometry(QtCore.QRect(470, 600, 52, 30))
        self.spinBox_24.setObjectName("spinBox_24")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(420, 720, 80, 21))
        self.label_26.setObjectName("label_26")
        self.spinBox_25 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_25.setGeometry(QtCore.QRect(470, 720, 52, 30))
        self.spinBox_25.setObjectName("spinBox_25")
        self.spinBox_26 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_26.setGeometry(QtCore.QRect(470, 560, 52, 30))
        self.spinBox_26.setObjectName("spinBox_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(420, 680, 80, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(550, 600, 80, 21))
        self.label_28.setObjectName("label_28")
        self.spinBox_27 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_27.setGeometry(QtCore.QRect(600, 640, 52, 30))
        self.spinBox_27.setObjectName("spinBox_27")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(550, 560, 80, 21))
        self.label_29.setObjectName("label_29")
        self.spinBox_28 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_28.setGeometry(QtCore.QRect(600, 680, 52, 30))
        self.spinBox_28.setObjectName("spinBox_28")
        self.spinBox_29 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_29.setGeometry(QtCore.QRect(600, 520, 52, 30))
        self.spinBox_29.setObjectName("spinBox_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(550, 520, 80, 21))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(550, 640, 80, 21))
        self.label_31.setObjectName("label_31")
        self.spinBox_30 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_30.setGeometry(QtCore.QRect(600, 600, 52, 30))
        self.spinBox_30.setObjectName("spinBox_30")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(550, 720, 80, 21))
        self.label_32.setObjectName("label_32")
        self.spinBox_31 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_31.setGeometry(QtCore.QRect(600, 720, 52, 30))
        self.spinBox_31.setObjectName("spinBox_31")
        self.spinBox_32 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_32.setGeometry(QtCore.QRect(600, 560, 52, 30))
        self.spinBox_32.setObjectName("spinBox_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(550, 680, 80, 21))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(670, 600, 80, 21))
        self.label_34.setObjectName("label_34")
        self.spinBox_33 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_33.setGeometry(QtCore.QRect(720, 640, 52, 30))
        self.spinBox_33.setObjectName("spinBox_33")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(670, 560, 80, 21))
        self.label_35.setObjectName("label_35")
        self.spinBox_34 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_34.setGeometry(QtCore.QRect(720, 680, 52, 30))
        self.spinBox_34.setObjectName("spinBox_34")
        self.spinBox_35 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_35.setGeometry(QtCore.QRect(720, 520, 52, 30))
        self.spinBox_35.setObjectName("spinBox_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(670, 520, 80, 21))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(670, 640, 80, 21))
        self.label_37.setObjectName("label_37")
        self.spinBox_36 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_36.setGeometry(QtCore.QRect(720, 600, 52, 30))
        self.spinBox_36.setObjectName("spinBox_36")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(670, 720, 80, 21))
        self.label_38.setObjectName("label_38")
        self.spinBox_37 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_37.setGeometry(QtCore.QRect(720, 720, 52, 30))
        self.spinBox_37.setObjectName("spinBox_37")
        self.spinBox_38 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_38.setGeometry(QtCore.QRect(720, 560, 52, 30))
        self.spinBox_38.setObjectName("spinBox_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(670, 680, 80, 21))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(790, 600, 80, 21))
        self.label_40.setObjectName("label_40")
        self.spinBox_39 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_39.setGeometry(QtCore.QRect(840, 640, 52, 30))
        self.spinBox_39.setObjectName("spinBox_39")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(790, 560, 80, 21))
        self.label_41.setObjectName("label_41")
        self.spinBox_40 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_40.setGeometry(QtCore.QRect(840, 680, 52, 30))
        self.spinBox_40.setObjectName("spinBox_40")
        self.spinBox_41 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_41.setGeometry(QtCore.QRect(840, 520, 52, 30))
        self.spinBox_41.setObjectName("spinBox_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(790, 520, 80, 21))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(790, 640, 80, 21))
        self.label_43.setObjectName("label_43")
        self.spinBox_42 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_42.setGeometry(QtCore.QRect(840, 600, 52, 30))
        self.spinBox_42.setObjectName("spinBox_42")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(790, 720, 80, 21))
        self.label_44.setObjectName("label_44")
        self.spinBox_43 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_43.setGeometry(QtCore.QRect(840, 720, 52, 30))
        self.spinBox_43.setObjectName("spinBox_43")
        self.spinBox_44 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_44.setGeometry(QtCore.QRect(840, 560, 52, 30))
        self.spinBox_44.setObjectName("spinBox_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(790, 680, 80, 21))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(910, 600, 80, 21))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(910, 560, 80, 21))
        self.label_47.setObjectName("label_47")
        self.spinBox_47 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_47.setGeometry(QtCore.QRect(960, 520, 52, 30))
        self.spinBox_47.setObjectName("spinBox_47")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(910, 520, 80, 21))
        self.label_48.setObjectName("label_48")
        self.spinBox_48 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_48.setGeometry(QtCore.QRect(960, 600, 52, 30))
        self.spinBox_48.setObjectName("spinBox_48")
        self.spinBox_50 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_50.setGeometry(QtCore.QRect(960, 560, 52, 30))
        self.spinBox_50.setObjectName("spinBox_50")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(540, 410, 171, 29))
        self.lineEdit.setObjectName("lineEdit")
        self.Frame = QtWidgets.QSlider(self.centralwidget)
        self.Frame.setGeometry(QtCore.QRect(260, 390, 801, 20))
        self.Frame.setOrientation(QtCore.Qt.Horizontal)
        self.Frame.setObjectName("Frame")
        self.Play = QtWidgets.QSlider(self.centralwidget)
        self.Play.setGeometry(QtCore.QRect(260, 360, 801, 18))
        self.Play.setOrientation(QtCore.Qt.Horizontal)
        self.Play.setObjectName("Play")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(1070, 360, 51, 29))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 410, 61, 30))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Anger.setText(_translate("MainWindow", "ANGER"))
        self.label_2.setText(_translate("MainWindow", "HAPPINESS"))
        self.Suprise.setText(_translate("MainWindow", "SUPRISE"))
        self.Disgust.setText(_translate("MainWindow", "DISGUST"))
        self.Distress.setText(_translate("MainWindow", "DISTRESS"))
        self.Fear.setText(_translate("MainWindow", "FEAR"))
        self.Embaressment.setText(_translate("MainWindow", "EMBARASSMENT"))
        self.Contemt.setText(_translate("MainWindow", "CONTEMPT"))
        self.label_9.setText(_translate("MainWindow", "1"))
        self.happiness.setText(_translate("MainWindow", "EXPRESSIONS"))
        self.label_11.setText(_translate("MainWindow", "2"))
        self.label_12.setText(_translate("MainWindow", "4"))
        self.label_13.setText(_translate("MainWindow", "3"))
        self.label_14.setText(_translate("MainWindow", "6"))
        self.label_15.setText(_translate("MainWindow", "5"))
        self.label_16.setText(_translate("MainWindow", "9"))
        self.label_17.setText(_translate("MainWindow", "8"))
        self.label_18.setText(_translate("MainWindow", "7"))
        self.label_19.setText(_translate("MainWindow", "10"))
        self.label_20.setText(_translate("MainWindow", "12"))
        self.label_21.setText(_translate("MainWindow", "11"))
        self.label_22.setText(_translate("MainWindow", "15"))
        self.label_23.setText(_translate("MainWindow", "14"))
        self.label_24.setText(_translate("MainWindow", "13"))
        self.label_25.setText(_translate("MainWindow", "16"))
        self.label_26.setText(_translate("MainWindow", "18"))
        self.label_27.setText(_translate("MainWindow", "17"))
        self.label_28.setText(_translate("MainWindow", "21"))
        self.label_29.setText(_translate("MainWindow", "20"))
        self.label_30.setText(_translate("MainWindow", "19"))
        self.label_31.setText(_translate("MainWindow", "22"))
        self.label_32.setText(_translate("MainWindow", "24"))
        self.label_33.setText(_translate("MainWindow", "23"))
        self.label_34.setText(_translate("MainWindow", "27"))
        self.label_35.setText(_translate("MainWindow", "26"))
        self.label_36.setText(_translate("MainWindow", "25"))
        self.label_37.setText(_translate("MainWindow", "28"))
        self.label_38.setText(_translate("MainWindow", "30"))
        self.label_39.setText(_translate("MainWindow", "29"))
        self.label_40.setText(_translate("MainWindow", "33"))
        self.label_41.setText(_translate("MainWindow", "32"))
        self.label_42.setText(_translate("MainWindow", "31"))
        self.label_43.setText(_translate("MainWindow", "34"))
        self.label_44.setText(_translate("MainWindow", "36"))
        self.label_45.setText(_translate("MainWindow", "35"))
        self.label_46.setText(_translate("MainWindow", "39"))
        self.label_47.setText(_translate("MainWindow", "38"))
        self.label_48.setText(_translate("MainWindow", "37"))
        self.lineEdit.setText(_translate("MainWindow", "Frame Number : "))
        self.pushButton.setText(_translate("MainWindow", "Pause"))


if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

